// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.21.12
// source: internal/handlers/proto_user/user.proto

package proto_user

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Email         string                 `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	Username      string                 `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	Password      string                 `protobuf:"bytes,3,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateUserRequest) Reset() {
	*x = CreateUserRequest{}
	mi := &file_internal_handlers_proto_user_user_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateUserRequest) ProtoMessage() {}

func (x *CreateUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_handlers_proto_user_user_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateUserRequest.ProtoReflect.Descriptor instead.
func (*CreateUserRequest) Descriptor() ([]byte, []int) {
	return file_internal_handlers_proto_user_user_proto_rawDescGZIP(), []int{0}
}

func (x *CreateUserRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *CreateUserRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *CreateUserRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type UserResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Email         string                 `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	Username      string                 `protobuf:"bytes,3,opt,name=username,proto3" json:"username,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,4,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     string                 `protobuf:"bytes,5,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserResponse) Reset() {
	*x = UserResponse{}
	mi := &file_internal_handlers_proto_user_user_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserResponse) ProtoMessage() {}

func (x *UserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_handlers_proto_user_user_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserResponse.ProtoReflect.Descriptor instead.
func (*UserResponse) Descriptor() ([]byte, []int) {
	return file_internal_handlers_proto_user_user_proto_rawDescGZIP(), []int{1}
}

func (x *UserResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UserResponse) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *UserResponse) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *UserResponse) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *UserResponse) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

type ListUserByIDRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListUserByIDRequest) Reset() {
	*x = ListUserByIDRequest{}
	mi := &file_internal_handlers_proto_user_user_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListUserByIDRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListUserByIDRequest) ProtoMessage() {}

func (x *ListUserByIDRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_handlers_proto_user_user_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListUserByIDRequest.ProtoReflect.Descriptor instead.
func (*ListUserByIDRequest) Descriptor() ([]byte, []int) {
	return file_internal_handlers_proto_user_user_proto_rawDescGZIP(), []int{2}
}

func (x *ListUserByIDRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type ListUserByEmailRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Email         string                 `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListUserByEmailRequest) Reset() {
	*x = ListUserByEmailRequest{}
	mi := &file_internal_handlers_proto_user_user_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListUserByEmailRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListUserByEmailRequest) ProtoMessage() {}

func (x *ListUserByEmailRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_handlers_proto_user_user_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListUserByEmailRequest.ProtoReflect.Descriptor instead.
func (*ListUserByEmailRequest) Descriptor() ([]byte, []int) {
	return file_internal_handlers_proto_user_user_proto_rawDescGZIP(), []int{3}
}

func (x *ListUserByEmailRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

type ListUserByUsernameRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListUserByUsernameRequest) Reset() {
	*x = ListUserByUsernameRequest{}
	mi := &file_internal_handlers_proto_user_user_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListUserByUsernameRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListUserByUsernameRequest) ProtoMessage() {}

func (x *ListUserByUsernameRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_handlers_proto_user_user_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListUserByUsernameRequest.ProtoReflect.Descriptor instead.
func (*ListUserByUsernameRequest) Descriptor() ([]byte, []int) {
	return file_internal_handlers_proto_user_user_proto_rawDescGZIP(), []int{4}
}

func (x *ListUserByUsernameRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

type ListUsersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Offset        int32                  `protobuf:"varint,1,opt,name=offset,proto3" json:"offset,omitempty"`
	Limit         int32                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListUsersRequest) Reset() {
	*x = ListUsersRequest{}
	mi := &file_internal_handlers_proto_user_user_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListUsersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListUsersRequest) ProtoMessage() {}

func (x *ListUsersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_handlers_proto_user_user_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListUsersRequest.ProtoReflect.Descriptor instead.
func (*ListUsersRequest) Descriptor() ([]byte, []int) {
	return file_internal_handlers_proto_user_user_proto_rawDescGZIP(), []int{5}
}

func (x *ListUsersRequest) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *ListUsersRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type ListUsersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Users         []*UserResponse        `protobuf:"bytes,1,rep,name=users,proto3" json:"users,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListUsersResponse) Reset() {
	*x = ListUsersResponse{}
	mi := &file_internal_handlers_proto_user_user_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListUsersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListUsersResponse) ProtoMessage() {}

func (x *ListUsersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_handlers_proto_user_user_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListUsersResponse.ProtoReflect.Descriptor instead.
func (*ListUsersResponse) Descriptor() ([]byte, []int) {
	return file_internal_handlers_proto_user_user_proto_rawDescGZIP(), []int{6}
}

func (x *ListUsersResponse) GetUsers() []*UserResponse {
	if x != nil {
		return x.Users
	}
	return nil
}

var File_internal_handlers_proto_user_user_proto protoreflect.FileDescriptor

const file_internal_handlers_proto_user_user_proto_rawDesc = "" +
	"\n" +
	"'internal/handlers/proto_user/user.proto\x12\n" +
	"proto_user\"a\n" +
	"\x11CreateUserRequest\x12\x14\n" +
	"\x05email\x18\x01 \x01(\tR\x05email\x12\x1a\n" +
	"\busername\x18\x02 \x01(\tR\busername\x12\x1a\n" +
	"\bpassword\x18\x03 \x01(\tR\bpassword\"\x8e\x01\n" +
	"\fUserResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05email\x18\x02 \x01(\tR\x05email\x12\x1a\n" +
	"\busername\x18\x03 \x01(\tR\busername\x12\x1d\n" +
	"\n" +
	"created_at\x18\x04 \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\x05 \x01(\tR\tupdatedAt\"%\n" +
	"\x13ListUserByIDRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\".\n" +
	"\x16ListUserByEmailRequest\x12\x14\n" +
	"\x05email\x18\x01 \x01(\tR\x05email\"7\n" +
	"\x19ListUserByUsernameRequest\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\"@\n" +
	"\x10ListUsersRequest\x12\x16\n" +
	"\x06offset\x18\x01 \x01(\x05R\x06offset\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x05R\x05limit\"C\n" +
	"\x11ListUsersResponse\x12.\n" +
	"\x05users\x18\x01 \x03(\v2\x18.proto_user.UserResponseR\x05users2\x9b\x03\n" +
	"\vUserService\x12G\n" +
	"\n" +
	"CreateUser\x12\x1d.proto_user.CreateUserRequest\x1a\x18.proto_user.UserResponse\"\x00\x12K\n" +
	"\fListUserByID\x12\x1f.proto_user.ListUserByIDRequest\x1a\x18.proto_user.UserResponse\"\x00\x12Q\n" +
	"\x0fListUserByEmail\x12\".proto_user.ListUserByEmailRequest\x1a\x18.proto_user.UserResponse\"\x00\x12W\n" +
	"\x12ListUserByUsername\x12%.proto_user.ListUserByUsernameRequest\x1a\x18.proto_user.UserResponse\"\x00\x12J\n" +
	"\tListUsers\x12\x1c.proto_user.ListUsersRequest\x1a\x1d.proto_user.ListUsersResponse\"\x00B Z\x1e./internal/handlers/proto_userb\x06proto3"

var (
	file_internal_handlers_proto_user_user_proto_rawDescOnce sync.Once
	file_internal_handlers_proto_user_user_proto_rawDescData []byte
)

func file_internal_handlers_proto_user_user_proto_rawDescGZIP() []byte {
	file_internal_handlers_proto_user_user_proto_rawDescOnce.Do(func() {
		file_internal_handlers_proto_user_user_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_handlers_proto_user_user_proto_rawDesc), len(file_internal_handlers_proto_user_user_proto_rawDesc)))
	})
	return file_internal_handlers_proto_user_user_proto_rawDescData
}

var file_internal_handlers_proto_user_user_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_internal_handlers_proto_user_user_proto_goTypes = []any{
	(*CreateUserRequest)(nil),         // 0: proto_user.CreateUserRequest
	(*UserResponse)(nil),              // 1: proto_user.UserResponse
	(*ListUserByIDRequest)(nil),       // 2: proto_user.ListUserByIDRequest
	(*ListUserByEmailRequest)(nil),    // 3: proto_user.ListUserByEmailRequest
	(*ListUserByUsernameRequest)(nil), // 4: proto_user.ListUserByUsernameRequest
	(*ListUsersRequest)(nil),          // 5: proto_user.ListUsersRequest
	(*ListUsersResponse)(nil),         // 6: proto_user.ListUsersResponse
}
var file_internal_handlers_proto_user_user_proto_depIdxs = []int32{
	1, // 0: proto_user.ListUsersResponse.users:type_name -> proto_user.UserResponse
	0, // 1: proto_user.UserService.CreateUser:input_type -> proto_user.CreateUserRequest
	2, // 2: proto_user.UserService.ListUserByID:input_type -> proto_user.ListUserByIDRequest
	3, // 3: proto_user.UserService.ListUserByEmail:input_type -> proto_user.ListUserByEmailRequest
	4, // 4: proto_user.UserService.ListUserByUsername:input_type -> proto_user.ListUserByUsernameRequest
	5, // 5: proto_user.UserService.ListUsers:input_type -> proto_user.ListUsersRequest
	1, // 6: proto_user.UserService.CreateUser:output_type -> proto_user.UserResponse
	1, // 7: proto_user.UserService.ListUserByID:output_type -> proto_user.UserResponse
	1, // 8: proto_user.UserService.ListUserByEmail:output_type -> proto_user.UserResponse
	1, // 9: proto_user.UserService.ListUserByUsername:output_type -> proto_user.UserResponse
	6, // 10: proto_user.UserService.ListUsers:output_type -> proto_user.ListUsersResponse
	6, // [6:11] is the sub-list for method output_type
	1, // [1:6] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_internal_handlers_proto_user_user_proto_init() }
func file_internal_handlers_proto_user_user_proto_init() {
	if File_internal_handlers_proto_user_user_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_handlers_proto_user_user_proto_rawDesc), len(file_internal_handlers_proto_user_user_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_internal_handlers_proto_user_user_proto_goTypes,
		DependencyIndexes: file_internal_handlers_proto_user_user_proto_depIdxs,
		MessageInfos:      file_internal_handlers_proto_user_user_proto_msgTypes,
	}.Build()
	File_internal_handlers_proto_user_user_proto = out.File
	file_internal_handlers_proto_user_user_proto_goTypes = nil
	file_internal_handlers_proto_user_user_proto_depIdxs = nil
}
